-- MySQL Script generated by MySQL Workbench
-- Monday 06 August 2018 01:20:11 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registration` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(10) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `contact` VARCHAR(10) NOT NULL,
  `email_id` VARCHAR(40) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `descp` VARCHAR(45) NOT NULL,
  `pattern` VARCHAR(45) NOT NULL,
  `image` TEXT(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `book_id_UNIQUE` (`book_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Advertisement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Advertisement` (
  `ad_id` INT NOT NULL,
  `create_date` DATE NULL,
  `Advertisementcol` VARCHAR(45) NULL,
  PRIMARY KEY (`ad_id`),
  UNIQUE INDEX `ad_id_UNIQUE` (`ad_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
